FROM springcloud/spring-cloud-skipper-server:2.1.0.RELEASE
COPY ./geode-processor/build/libs/geode-processor-0.0.1-SNAPSHOT.jar /processor/geode/geode-processor-0.0.1-SNAPSHOT.jar
COPY ./postgres-processor/build/libs/postgres-processor-0.0.1-SNAPSHOT.jar /processor/postgres/postgres-processor-0.0.1-SNAPSHOT.jar