{
 "title": "RabbitMQ Metrics",
 "description": "Basic rabbitmq host stats: Node Stats, Exchanges, Channels, Consumers,  Connections, Queues, Messages, Messages per Queue, Memory, File Descriptors, Sockets.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Server",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rabbitmq_up" }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_running", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_exchangesTotal", "legendFormat": "{{instance}}:exchanges" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channelsTotal", "legendFormat": "{{instance}}:channels" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumersTotal", "legendFormat": "{{instance}}:consumers" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connectionsTotal", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queuesTotal", "legendFormat": "{{instance}}:queues" }
   ]
  },
  {
   "title": "Messages/host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready)",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}:{{durable}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_mem_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_node_mem_limit", "legendFormat": "{{node}}:limit" }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_fd_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_fd_total", "legendFormat": "{{node}}:total" }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_sockets_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_sockets_total", "legendFormat": "{{node}}:total" }
   ]
  }
 ]
}